import Head from 'next/head';
import Image from 'next/image';
import Three from '../components/three';
import Three_2 from '../components/three_2';

import { useState } from 'react';

export default function Home() {
  const [color, setColor] = useState(Math.floor(Math.random() * 16777215).toString(16));

  return (
    <div>
      <Head>
        <title>Boilerplate NEXThreeTailwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" bg-black w-full ">
        <h1
          className="text-4xl md:text-6xl text-white text-center py-8 font-bold
        text-transparent bg-clip-text bg-gradient-to-br from-gray-600 to-white"
        >
          Next.js + Three.js + Tailwindcss
        </h1>
      </div>

      <div
        className="flex w-full flex-col md:flex-row items-center justify-center relative -mt-2 overflow-hidden"
        onClick={() => setColor(Math.floor(Math.random() * 16777215).toString(16))}
      >
        <Three color={color} />
        <div className="flex flex-col items-center p-12  absolute top-0">
          <h1 className="text-white text-center -mb-12 text-xs">Created by</h1>
          <Image src={'/black.svg'} height="220" width="220" alt="black" />
        </div>
      </div>

      <div className="flex w-full flex-col md:flex-row max-w-4xl my-8 mx-auto px-8">
        <h1 className="text-6xl font-bold mr-10 mb-8 md:mb-0">Next.js + Three.js + Tailwindcss</h1>
        <p>
          Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has
          been the industrys standard dummy text ever since the 1500s, when an unknown printer took
          a galley of type and scrambled it to make a type specimen book. It has survived not only
          five centuries, but also the leap into electronic typesetting, remaining essentially
          unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
          Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
          PageMaker including versions of Lorem Ipsum.
        </p>
      </div>

      <div className="flex w-full flex-col md:flex-row items-center justify-center relative -mt-2 overflow-hidden">
        <Three_2 />
        <div className="flex flex-col items-center p-12  absolute left-0 top-0 w-1/2">
          <Image src={'/black.svg'} height="220" width="220" alt="black" />
          <p className="text-white">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
            has been the industrys standard dummy text ever since the 1500s, when an unknown printer
            took a galley of type and scrambled it to make a type specimen book. It has survived not
            only five centuries, but also the leap into electronic typesetting, remaining
            essentially unchanged. It was popularised in the 1960s with the release of Letraset
            sheets containing Lorem Ipsum passages, and more recently with desktop publishing
            software like Aldus PageMaker including versions of Lorem Ipsum.
          </p>
        </div>
      </div>
    </div>
  );
}
