import Head from 'next/head';
import Image from 'next/image';
import Three from '../components/three';
import Three_2 from '../components/three_2';
import Three_3 from '../components/three_3';
import Three_4 from '../components/three_4';
import { useState } from 'react';

export default function Home() {
  const [color, setColor] = useState(Math.floor(Math.random() * 16777215).toString(16));
  const [lightsOn, setLightsOn] = useState(true);

  return (
    <div>
      <Head>
        <title>Boilerplate NEXThreeTailwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" bg-black w-full ">
        <h1
          className="text-4xl md:text-6xl text-white text-center py-8 font-bold
        text-transparent bg-clip-text bg-gradient-to-br from-gray-600 to-white"
        >
          Next.js + Three.js + Tailwindcss
        </h1>
      </div>
      {/* Three_1 */}
      <div
        className="flex w-full flex-col md:flex-row items-center justify-center relative -mt-2 overflow-hidden"
        onClick={() => setColor(Math.floor(Math.random() * 16777215).toString(16))}
      >
        <Three color={color} />
        <div className="flex flex-col items-center p-12  absolute top-0">
          <h1 className="text-white text-center -mb-12 text-xs">Created by</h1>
          <Image src={'/black.svg'} height="220" width="220" alt="black" />
        </div>
      </div>

      <div className="flex w-full flex-col md:flex-row max-w-4xl my-8 mx-auto px-8">
        <h1 className="text-6xl font-bold mr-10 mb-8 md:mb-0">Next.js + Three.js + Tailwindcss</h1>
        <p>
          Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has
          been the industrys standard dummy text ever since the 1500s, when an unknown printer took
          a galley of type and scrambled it to make a type specimen book. It has survived not only
          five centuries, but also the leap into electronic typesetting, remaining essentially
          unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
          Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
          PageMaker including versions of Lorem Ipsum.
        </p>
      </div>
      <div className="h-px w-full bg-black mx-auto self-center" />

      {/* Three_2 */}
      <div className="flex w-full flex-col md:flex-row items-center justify-center  overflow-hidden mt-12">
        <Three_2 />
        <div className="flex flex-col items-center md:w-1/2 px-12">
          <h1
            className="text-6xl text-white py-8 font-bold
        text-transparent bg-clip-text bg-gradient-to-br from-pink-600 to-blue-400 self-start"
          >
            Half width
          </h1>
          <p className="text-black">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
            has been the industrys standard dummy text ever since the 1500s, when an unknown printer
            took a galley of type and scrambled it to make a type specimen book. It has survived not
            only five centuries, but also the leap into electronic typesetting, remaining
            essentially unchanged. It was popularised in the 1960s with the release of Letraset
            sheets containing Lorem Ipsum passages, and more recently with desktop publishing
            software like Aldus PageMaker including versions of Lorem Ipsum.
          </p>
        </div>
      </div>
      {/* Three_3 */}

      <div className="flex w-full flex-col  items-center justify-center  overflow-hidden mt-12">
        <div className="flex flex-col items-center  px-12 my-12">
          <h1
            className="text-6xl text-white text-start py-8 font-bold
        text-transparent bg-clip-text bg-gradient-to-br from-green-400 to-pink-400"
          >
            Half height + matcap + gsap
          </h1>
          <p className="text-black">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
            has been the industrys standard dummy text ever since the 1500s, when an unknown printer
            took a galley of type and scrambled it to make a type specimen book. It has survived not
            only five centuries, but also the leap into electronic typesetting, remaining
            essentially unchanged. It was popularised in the 1960s with the release of Letraset
            sheets containing Lorem Ipsum passages, and more recently with desktop publishing
            software like Aldus PageMaker including versions of Lorem Ipsum.
          </p>
        </div>
        <div className="h-px w-full bg-black mx-auto self-cente " />
        <div className="h-2 w-full bg-black mx-auto self-center my-2" />
        <Three_3 />
        <div className="h-2 w-full bg-black mx-auto self-cente my-2" />
        <div className="h-[5px] w-full bg-black mx-auto self-center" />
        <div className="h-[3px] w-full bg-black mx-auto self-center mt-1" />
      </div>

      <div
        className={`flex w-full flex-col md:flex-row items-center justify-center  overflow-hidden mt-12  mb-8 ${
          lightsOn ? 'bg-white' : 'bg-black'
        }`}
      >
        <div className="flex flex-col items-center md:w-1/2 px-12">
          <h1
            className={`text-6xl py-8 font-bold self-start ${
              lightsOn
                ? 'text-black'
                : 'text-transparent bg-clip-text bg-gradient-to-br from-pink-600 to-blue-400'
            }`}
          >
            Half width
          </h1>
          <p className={` ${lightsOn ? 'text-black' : 'text-white'}`}>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
            has been the industrys standard dummy text ever since the 1500s, when an unknown printer
            took a galley of type and scrambled it to make a type specimen book. It has survived not
            only five centuries, but also the leap into electronic typesetting, remaining
            essentially unchanged. It was popularised in the 1960s with the release of Letraset
            sheets containing Lorem Ipsum passages, and more recently with desktop publishing
            software like Aldus PageMaker including versions of Lorem Ipsum.
          </p>
          {lightsOn ? (
            <button onClick={() => setLightsOn(!lightsOn)}>Lights off</button>
          ) : (
            <button className="text-white border-2 p-2" onClick={() => setLightsOn(!lightsOn)}>
              Lights on
            </button>
          )}
        </div>
        <Three_4 lightsOn={lightsOn} />
      </div>
    </div>
  );
}
